server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5433/careeros
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

management.endpoint.health.probes.enabled=true

# ===============================
# Actuator / Prometheus
# ===============================
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always

management.metrics.tags.application=${spring.application.name}
management.metrics.distribution.percentiles-histogram.http.server.requests=true

# ===============================
# Distributed tracing
# ===============================
management.tracing.enabled=true
management.tracing.sampling.probability=1.0

# Tempo OTLP endpoint
management.otlp.tracing.endpoint=http://localhost:4318/v1/traces

# ===========================
# LOGGING
# ===========================

# Current active log file
logging.file.name=logs/auth-service.log

# Archive old logs daily and whenever the active file reaches 10 MB
logging.logback.rollingpolicy.file-name-pattern=logs/auth-service.%d{yyyy-MM-dd}.%i.log.gz
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=14
logging.logback.rollingpolicy.total-size-cap=500MB

# Console log format
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [thread=%thread,id=%tid] [traceId=%X{traceId:-},spanId=%X{spanId:-}] %logger{36} - %msg%n

# File log format
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [thread=%thread,id=%tid] [traceId=%X{traceId:-},spanId=%X{spanId:-}] %logger{36} - %msg%n

# ===============================
# Flyway database migrations
# ===============================
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# ===============================
# JWT
# ===============================
security.jwt.secret=CareerOSJwtSecretKeyForDevelopmentOnlyChangeThisBeforeProduction123456
security.jwt.access-token-expiration-ms=900000
security.jwt.refresh-token-expiration-days=30

rabbitmq.exchange=careeros.events

rabbitmq.routing-key.user-registered=user.registered