server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5433/careeros
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
